const tagsData = {
    tags: [

       // status: number
            // 1: normal, 2: extreme, 3: obsolete

       // comment: "string",
        // comment: null
            // for no comments 

        // slaveTagIds: [id, id, id]
            // For master tags

        {
            name: "RenPy",
            description: "Games made using Ren'Py visual novel engine",
            category: "Engine",
            comment: "Common in visual novels and dating sims",
            status: 1,
        },
        {
            name: "Unity3D",
            description: "Games developed using Unity 3D engine",
            category: "Engine",
            comment: null,
            status: 1,
        },
        {
            name: "UnrealEngine",
            description: "Games developed using UE engine",
            category: "Engine",
            comment: null,
            status: 1,
        },
        {
            name: "RPGM",
            description: "Games developed using RPG Maker engine",
            category: "Engine",
            comment: "Common for RPG games",
            status: 1,
        },
        {
            name: "HTML",
            description: "Games developed using HTML file format",
            category: "Engine",
            comment: "Common for Text-based games",
            status: 1,
        },
        {
            name: "Java",
            description: "Games developed using JS file format",
            category: "Engine",
            comment: null,
            status: 1,
        },
        {
            name: "Flash",
            description: "Games that made in Adobe Flash",
            category: "Engine",
            comment: "Common for web browser games",
            status: 1,
        },
        {
            name: "Others",
            description: "Games that do not come up with engines listed on Engine tab",
            category: "Engine",
            comment: null,
            status: 1,
        },



        {
            name: "2D-game",
            description: "Games that only use 2 dimensions to build a game",
            category: "Technical",
            comment: null,
            status: 1,
        },
        {
            name: "2D-cg",
            description: "Games that use 2 dimensions for their image illustrations",
            category: "Technical",
            comment: null,
            status: 1,
        },
        {
            name: "3D-game",
            description: "Games that use 3 dimensions to build a game",
            category: "Technical",
            comment: null,
            status: 1,
        },
        {
            name: "3D-cg",
            description: "Games that use 3 dimensions for their image illustrations",
            category: "Technical",
            comment: null,
            status: 1,
        },
        {
            name: "AI-cg",
            description: "Games that use AI generation to illustrate images",
            category: "Technical",
            comment: null,
            status: 1,
        },
        {
            name: "Animated",
            description: "Sex scenes are is animated",
            category: "Technical",
            comment: null,
            status: 1,
        },
        {
            name: "RealLife",
            description: "[TBD]",
            category: "Technical",
            comment: "Really?",
            status: 1,
        },
        {
            name: "Voiced",
            description: "Text is fully or partially voiced by voice actors",
            category: "Technical",
            comment: null,
            status: 1,
        },
        
        


        {
            name: "Japanese",
            description: "Japanese language",
            category: "Language",
            comment: null,
            status: 1,
        },
        {
            name: "Korean",
            description: "Korean language",
            category: "Language",
            comment: null,
            status: 1,
        },
        {
            name: "English",
            description: "English language",
            category: "Language",
            comment: null,
            status: 1,
        },
        {
            name: "Russian",
            description: "Russian language",
            category: "Language",
            comment: null,
            status: 1,
        },
        {
            name: "Other-language",
            description: "Any other language",
            category: "Language",
            comment: null,
            status: 1,
        },




        {
            name: "Ahegao",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            id: 1,
            name: "age-difference",
            description: "Significant age gap between characters",
            category: "Kinks",
            aliases: ["age"],
            status: 2,
            comment: "Includes various age-gap relationships",
            slaveTagIds: [2, 3]
        },
        {
            name: "Anal-sex",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "BDSM",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Bestiality",
            description: "Sexual acts involving animals.",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Bimbofication",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Body-Modification",
            description: "Extreme alterations to the body for sexual pleasure.",
            category: "Kinks",
            status: 2,
            comment: "Subcategories might include scarification, branding, piercings, etc."
        },
        {
            name: "Bukkake",
            description: "Sex act in which one participant is ejaculated on by multiple participants",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Blackmail",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Cheating",
            description: "Sexual contact with someone other than their partner, without approval from their partner",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Creampie",
            description: "Semen leaks from a woman's vagina after sex",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Corruption",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Cosplay",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Drugs",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            id: 2,
            name: "Dilf",
            description: "Older male character",
            category: "Kinks",
            aliases: ["daddy", "dad"],
            status: 1,
            masterTagId: 1,
            comment: null
        },
        {
            name: "Exhibitionism",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "FemDom",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "FemSub",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        
        {
            name: "FootJob",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Furry",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Futanari",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Homosexual",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Groping",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Gore",
            description: "Contains graphic violence and blood",
            category: "Kinks",
            comment: "Usually present in horror games",
            status: 2,
        },
        {
            name: "Handjob",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Exhibitionism",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Humilation",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Incest",
            description: "Sexual relations between family members.",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Lactation",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Lolicon",
            description: "Sexual attraction to prepubescent female children",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Masturbation",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            id: 3,
            name: "Milf",
            description: "Older female character",
            category: "Kinks",
            aliases: ["mommy", "mom"],
            status: 1,
            masterTagId: 1,
            comment: null
        },
        {
            name: "MindControl",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Necrophilia",
            description: "Sexual attraction to corpses.",
            category: "Kinks",
            status: 2,
        },
        {
            name: "Netorare",
            description: "Sexual contact with someone other than the partner, without the partner's approval and without the victim's consent",
            category: "Kinks",
            comment: "Extreme Version of Cheating",
            status: 2,
        },
        {
            name: "OralSex",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Posession",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Pregnancy",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Prostitution",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Rape",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Scat",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Shota",
            description: "Sexual attraction to prepubescent male children",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Sissification",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Spanking",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Stripping",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Teasing",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 1,
        },
        {
            name: "Titfuck",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Transformation",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Urination",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Vaginal-Sex",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Vanilla",
            description: "[TBD]",
            category: "Kinks",
            comment: "Everyone has their own tastes i guess...",
            status: 1,
        },
        {
            name: "Vore",
            description: "[TBD]",
            category: "Kinks",
            comment: null,
            status: 2,
        },
        {
            name: "Voyeurism",
            description: "A sexual interest in or practice of watching other people engaged in intimate behaviors",
            category: "Kinks",
            comment: null,
            status: 1,
        },




        {
            name: "Adventure",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
    {
            name: "DateSim",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Dystopy",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Fantasy",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Horror",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Harem",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "KineticNovel",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Management",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Multiple-Endings",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "No-Sex",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Paranormal",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Parody",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Platformer",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Point-n-Click",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Puzzle",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            id: 4,
            name: "RPG",
            description: "Role-playing games with character development and storytelling",
            category: "Genre",
            aliases: ["roleplay-game", "role-playing-game"],
            status: 1,
            comment: "Common in story-driven games",
            slaveTagIds: []
        },
        {
            name: "Sandbox",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Sci-Fi",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "School",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Shooter",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Side-scroller",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "School",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Simulator",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Strategy",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Text-based",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Turn-based",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "School",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "Trainer",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },
        {
            name: "VisualNovel",
            description: "[TBD]",
            category: "Genre",
            comment: null,
            status: 1,
        },




        {
            name: "Alien",
            description: "Features extraterrestrial characters",
            category: "Characters",
            comment: "Includes both humanoid and non-humanoid aliens",
            status: 1,
        },



        {
            name: "MTL",
            description: "Games that use automatic machine translation to adapt user's language",
            category: "Meta",
            comment: null,
            status: 1,
        },
        {
            name: "Full-censorsip",
            description: "[TBD]",
            category: "Meta",
            comment: null,
            status: 1,
        },
        {
            name: "Mosaic-censorsip",
            description: "[TBD]",
            category: "Meta",
            comment: null,
            status: 1,
        },
        {
            name: "Uncensored",
            description: "[TBD]",
            category: "Meta",
            comment: null,
            status: 1,
        },
        {
            name: "Translated",
            description: "[TBD]",
            category: "Meta",
            comment: null,
            status: 1,
        },
        {
            name: "Rough-translation",
            description: "Any 3rd party translation consisting of a required amount of text boxes/bubbles with a translation error.",
            category: "Meta",
            comment: "Should NOT be confused with rough grammar.",
            status: 1,
        },
        {
            name: "Rough-grammar",
            description: "Any 3rd party translation consisting of a required amount of sentences with a grammatical or spelling error.",
            category: "Meta",
            comment: "Translations containing grammatical or spelling errors that occurred in the original work are excluded.",
            status: 1,
        },
        {
            name: "Speechless",
            description: "A game with no narration or speech",
            category: "Meta",
            comment: null,
            status: 1,
        },
    ]
};